apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    owner: yash
  name: clusterpedia-apiserver
  namespace: clusterpedia-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    owner: yash
  name: clusterpedia-apiserver
  namespace: clusterpedia-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: clusterpedia-apiserver
    owner: yash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clusterpedia-apiserver
    owner: yash
  name: clusterpedia-apiserver
  namespace: clusterpedia-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterpedia-apiserver
      owner: yash
  template:
    metadata:
      labels:
        app: clusterpedia-apiserver
        owner: yash
    spec:
      containers:
      - command:
        - /usr/local/bin/apiserver
        - --secure-port=443
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        - -v=3
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: internalstorage-password
        image: ghcr.io/clusterpedia-io/clusterpedia/apiserver:v0.7.0
        name: apiserver
        volumeMounts:
        - mountPath: /etc/clusterpedia/storage
          name: internalstorage-config
          readOnly: true
      serviceAccountName: clusterpedia-apiserver
      volumes:
      - configMap:
          name: clusterpedia-internalstorage
        name: internalstorage-config
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    owner: yash
  name: v1beta1.clusterpedia.io
spec:
  group: clusterpedia.io
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: clusterpedia-apiserver
    namespace: clusterpedia-system
  version: v1beta1
  versionPriority: 100
