apiVersion: v1
data:
  mongo-password: bW9uZ29wYXNzd29yZA==
  mongo-user: bW9uZ291c2Vy
kind: Secret
metadata:
  labels:
    client: google
  name: mongo-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    client: google
  name: webapp-service
spec:
  ports:
  - nodePort: 30100
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: webapp
    client: google
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
    client: google
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      client: google
  template:
    metadata:
      labels:
        app: webapp
        client: google
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: mongo-url
              name: mongo-config
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongo-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-password
              name: mongo-secret
        image: mongo-express:latest
        name: webapp
        ports:
        - containerPort: 8081
