apiVersion: v1
data:
  mongo-url: mongo-service
kind: ConfigMap
metadata:
  labels:
    app: myword
  name: mongo-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myword
  name: mongo-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: myword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myword
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myword
  template:
    metadata:
      labels:
        app: myword
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongo-secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-password
              name: mongo-secret
        image: mongo:5.0
        name: mongo
        ports:
        - containerPort: 27017
